### PR TITLE
Move TopcomInterface to ToricVarieties_project

### PR DESCRIPTION
**Pull request by HereAround**

### CODE REVIEW

**Comment by HereAround** [comment]
@mohamed-barakat : I need to investigate in more detail why the tests for this PR fail. This was meant as notification of moving this package, so that - once it has been moved - you can remove the old repository https://github.com/homalg-project/TopcomInterface.

**Comment by mohamed-barakat** [comment]
Good. I will be notified once this is merged :)

**Comment by HereAround** [comment]
@mohamed-barakat This PR finally passes the tests. I will rebase and merge now. Consequently, `TopcomInterface` (including its history) is then integrated into the `ToricVarieties_project`, so that you can delete the old repository: https://github.com/homalg-project/TopcomInterface.

**Comment by mohamed-barakat** [comment]
Very good. Done.

**Pull request merged**
