### PR TITLE
An attempt to merge ToricVarieties

### PR DESCRIPTION
**Pull request by HereAround**
I proceeded as follows:

* https://coderwall.com/p/a3a5xg/splitting-a-project-sub-directory-to-a-new-git-repo
I thus issued:
git subtree split -P ToricVarieties -b TVIsolated
The resulting repository with only ToricVarieties has been placed at https://github.com/HereAround/IsolatedToricVarieties
* https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another/32684503
This allowed me to add ToricVarieties as subfolder to SheafCohomologies

Is there a conflict (<-> proper subtree merges) and if so, how can we correct that?

See also https://github.com/homalg-project/homalg_project/pull/334, where I am proposing a way to remove ToricVarieties from the homalg_project.

### CODE REVIEW

**Review by zickgraf — APPROVED** [review]
This looks fine (i.e. like a proper subtree merge) to me :-)

Important: to really make it a proper subtree merge, do NOT use the merge button, but instead push the HEAD of the `WithTV` branch directly to master (which should be a fast-forward since you have already created a merge commit)!

**Comment by zickgraf** [comment]
Note: As far as I can tell you did not use `git subtree` to merge `ToricVarieties` into `SheafCohomologyOnToricVarieties` but instead manually moved it into a subdirectory in commit ecb003b8b295e79c0bd98bd439096cf833354402. This does not confuse my "lines of code" script, but using
```
git subtree add --prefix=ToricVarieties /path/to/IsolatedToricVarieties master
```
instead would allow you to use all `git subtree` features (which you probably do not need in this case since this is a one-time-merge, I assume :D ).

**Comment by HereAround** [comment]
> This looks fine (i.e. like a proper subtree merge) to me :-)
> 
> Important: to really make it a proper subtree merge, do NOT use the merge button, but instead push the HEAD of the `WithTV` branch directly to master (which should be a fast-forward since you have already created a merge commit)!

Thank you for the pointer. Once @mohamed-barakat approves this PR, I will do it this way.

**Comment by HereAround** [comment]
> Note: As far as I can tell you did not use `git subtree` to merge `ToricVarieties` into `SheafCohomologyOnToricVarieties` but instead manually moved it into a subdirectory in commit [ecb003b](https://github.com/homalg-project/SheafCohomologyOnToricVarieties/commit/ecb003b8b295e79c0bd98bd439096cf833354402). This does not confuse my "lines of code" script, but using
> 
> ```
> git subtree add --prefix=ToricVarieties /path/to/IsolatedToricVarieties master
> ```
> 
> instead would allow you to use all `git subtree` features (which you probably do not need in this case since this is a one-time-merge, I assume :D ).

Exactly. I will bare this solution in mind, in case such a situation appears again in the future.

**Comment by mohamed-barakat** [comment]
Since GAP does not support meta-packages yet, `ToricVarieties` is deposited as a separate package.

In the future, you have to take over the release process. We can talk about the details later on. In particular, you need a branch called gh-pages and files like

* [`make_dist_for_homalg.sh`](https://github.com/homalg-project/homalg_project/blob/master/make_dist_for_homalg.sh)
* [`release`](https://github.com/homalg-project/homalg_project/blob/master/release)
* [`delete_old_releases.py`](https://github.com/homalg-project/homalg_project/blob/master/delete_old_releases.py)

And since you cannot release your entire repository as one (meta-)package, you have no alternative than continuing to distribute `ToricVarieties` from your new subdirectory `ToricVarieties`.

**Review by mohamed-barakat — APPROVED** [review]

**Comment by mohamed-barakat** [comment]
@zickgraf: We should also think of including `SheafCohomologyOnToricVarieties` into our test-suite. At least we should continue to test `ToricVarieties` for Martin not to release broken versions.

**Comment by mohamed-barakat** [comment]
Please do not merge until tomorrow, and do not use the merge button. I would like to make the corresponding deletions in `homalg_project`. The merge here and the deletion there should happen on the same day.

**Comment by zickgraf** [comment]
> At least we should continue to test ToricVarieties for Martin not to release broken versions.

At the moment `ToricVarieties` is not part of the test suite for the following reason: Some of its tests need the package `TopcomInterface` which is not available in our CI. I wanted to conditionally disable the tests depending on `TopcomInterface`, but ran into the issue described in this PR: https://github.com/gap-system/gap/pull/3931 I have backported the PR to `stable-4.11`, so it will be included in the next point release of GAP.

**Comment by mohamed-barakat** [comment]
> At the moment `ToricVarieties` is not part of the test suite for the following reason: Some of its tests need the package `TopcomInterface` which is not available in our CI. I wanted to conditionally disable the tests depending on `TopcomInterface`, but ran into the issue described in this PR: [gap-system/gap#3931](https://github.com/gap-system/gap/pull/3931) I have backported the PR to `stable-4.11`, so it will be included in the next point release of GAP.

Thank you very much @zickgraf.

**Comment by HereAround** [comment]
Agreed. Let us discuss all of this in more detail. And no, I am not going to merge until I hear your "go". Thank you!

**Comment by HereAround** [comment]
> > At least we should continue to test ToricVarieties for Martin not to release broken versions.
> 
> At the moment `ToricVarieties` is not part of the test suite for the following reason: Some of its tests need the package `TopcomInterface` which is not available in our CI. I wanted to conditionally disable the tests depending on `TopcomInterface`, but ran into the issue described in this PR: [gap-system/gap#3931](https://github.com/gap-system/gap/pull/3931) I have backported the PR to `stable-4.11`, so it will be included in the next point release of GAP.

A few comments regarding the tests with ```TopcomInterface```: 

* @kamalsaleh and I made ```TopcomInterface``` a suggested package for ```NConvex```. This is where ```TopcomInterface``` links naturally, since it computes triangulations of fans, and fans are supported by NConvex.
* Your comment indicates, that we currently do not have tests in ```NConvex```, which test the functionality of ```TopcomInterface```. @KamalSaleh Does it make sense to add such tests? (Also since ```NConvex``` is released, but ```TopcomInterface``` is not.)
* @Zickgraf - a quick way to fix your tests, is for me to move the tests in ```ToricVarieties```, which rely on ```TopcomInterface```, e.g. into my ```AdditionForToricVarieties```. I can do this very quickly, once ```ToricVarieties``` is part of the ```SheafCohomologies```.
* However, I would appreciate if we could extend your tests to ideally cover the entire ```SheafCohomologies```. My past experience is, that these tests are very sensitive to changes anywhere in the homalg_project.

**Comment by mohamed-barakat** [comment]
This can be manually merged now, i.e., without using the merge button or creating a merge commit.

**Comment by kamalsaleh** [comment]
`NConvex` is not included yet in the `homalg_project` test suits. But, still your conclusion is true. `NConvex` doens't test the functionality of `TopcomInterface`, since the latter is a suggested package.

**Comment by HereAround** [comment]
I have now 'merged' ToricVarieties;

* As proposed by @zickgraf 
   ```git subtree add --prefix=ToricVarieties /path/to/IsolatedToricVarieties master```
* This then results in this one commit here: https://github.com/homalg-project/SheafCohomologyOnToricVarieties/commit/7c7658ae69d340985209e5f1777ff713b4c60b51

Are we all happy with this change?

I leave this PR open for discussion (e.g. regarding tests and release processes). Alternatively, we can also discuss at https://github.com/homalg-project/SheafCohomologyOnToricVarieties/issues/28.

**Comment by mohamed-barakat** [comment]
I am confused. If you push what you have manually merged this PR should be closed, or not?

**Comment by HereAround** [comment]
This is because of the following:

* In this PR there are two commits associated with adding ToricVarieties to SheafCohomologies.
This results from following the procedure outlined in the first answer here: https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another/32684503
* I believe the method by @zickgraf is better. By using it, there is only the single commit "Add 'ToricVarieties/' from commit '5d28c605d6e5eae61b245ee0f36d1b5373… ".

For this reason, my push has not been a fast forward and this PR has not been closed automatically.

**Comment by mohamed-barakat** [comment]
Got it, thank you for elaborating. I would still close this PR manually and we can continue discussions somewhere else if needed.

**Comment by HereAround** [comment]
As suggested - I close this PR now. We can discuss e.g. in https://github.com/homalg-project/SheafCohomologyOnToricVarieties/issues/28 or you open a new issue (regarding e.g. distribution of ToricVarieties).

**Pull request closed without merging**
