### PR TITLE
Add lines to CI which test the ToricVarieties_project

### PR DESCRIPTION
**Pull request by HereAround**
A simple test suite with github actions for the ToricVarieties project. This covers all but the packages
* SparseMatrices
* SpasmInterface
* SheafCohomologies
* CoherentSheaves

### CODE REVIEW

**Review by zickgraf — COMMENTED** [review]
We do not use GitHub Actions in our CI, so I cannot really review this. But one general remark: in our CI I have separated the basic setup (which depends on the system and CI service used) from the actual tests. This way, we can use multiple CI services (like CircleCI and Jenkins) with little code duplication (cf. https://github.com/homalg-project/homalg_project/blob/master/.circleci/config.yml and https://github.com/homalg-project/homalg_project/blob/master/Jenkinsfile: all the "magic" happens inside of `make ci-test`, everything else is system and service specific setup).

**Comment by zickgraf** [comment]
Additional note: It seems like you do not use the checked out version in $GITHUB_WORKSPACE, but always the master branch by cloning `ToricVarieties_project` manually. Thus, the CI runs on pull requests but actually tests the master branch.

**Comment by zickgraf** [comment]
I have taken a look at GitHub Actions some months ago but could not get it to work back than. After seeing your PR I decided to give it another try, the result is here: https://github.com/zickgraf/homalg_project/blob/aaade703d9b1443f0d1ba1775b976c6992d262e3/.github/workflows/ci.yml It uses the official docker images, so I don't have to setup GAP and dependencies.

**Comment by HereAround** [comment]
Thank you for these pointers Fabian. I am looking into this again very soon.

**Comment by HereAround** [comment]
> Additional note: It seems like you do not use the checked out version in $GITHUB_WORKSPACE, but always the master branch by cloning `ToricVarieties_project` manually. Thus, the CI runs on pull requests but actually tests the master branch.

**Comment by HereAround** [comment]
@zickgraf

My current attempt to perform the tests for ToricVarieties via `TERM=dumb make -j $(nproc) --output-sync ci-test` fails with the message below. I suppose the tests of ToricVarieties in the homalg_project do not run into the same trouble? Any suggestions?

Error, no method found! For debugging hints type ?Recovery from NoMethodFound
(cd tst ; ./clean)
Error, no 1st choice method found for `SetPrintFormattingStatus' on 2 argument\
gap makedoc.g
s
 *********   GAP 4.11.0 of 29-Feb-2020
The 1st argument is 'fail' which might point to an earlier problem
 at /home/gap/inst/gap-4.11.0/lib/methsel2.g:249 called from
SetPrintFormattingStatus( filestream, false 
 ); at /home/gap/.gap/pkg/AutoDoc/gap/ToolFunctions.gi:54 called from
AUTODOC_OutputTextFile( dir, "title.xml" 
 ) at /home/gap/.gap/pkg/AutoDoc/gap/AutoDocMainFunction.gi:227 called from
CreateTitlePage( doc_dir, title_page 
 ); at /home/gap/.gap/pkg/AutoDoc/gap/Magic.gi:499 called from
<function "AutoDoc">( <arguments> )
 called from read-eval loop at makedoc.g:17
type 'quit;' to quit to outer loop
brk> Reading file "makedoc.g" has been aborted.
/usr/bin/time: performance.out: Permission denied
make: *** [test-with-coverage] Error 1
 *  GAP  *   https://www.gap-system.org
 *********   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...

 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, 
             AutPGrp 1.10.2, Browse 1.8.8, CaratInterface 2.3.3, CRISP 1.4.5, 
             Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, 
             Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, 
             ResClasses 4.7.2, SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
Generating documentation in Directory("./doc/")
gap> /usr/bin/time --quiet --format="%U %S\n%e" --output=performance.out gap --quitonbreak --cover stats tst/testall.g
makefile:19: recipe for target 'test-with-coverage' failed
Error: Process completed with exit code 2.

**Comment by HereAround** [comment]
It seems I finally produced a first working example.

**Comment by zickgraf** [comment]
> It seems I finally produced a first working example.

So the question above is obsolete?

**Comment by HereAround** [comment]
> > It seems I finally produced a first working example.
> 
> So the question above is obsolete?

Yes, that particular question is obsolete (unless you encounter this specific error).

I am not yet satisfied with the current solution because:

1. Only a subset of the tests run (namely those of the ToricVarieties package).
2. I install Singular and 4ti2. Maybe the performance can be increased by use of https://github.com/gap-system/gap-docker-base.
3. Same question for CddInterface and NormalizInterface. Maybe those are included in https://github.com/gap-system/gap-docker?

**Comment by zickgraf** [comment]
> I install Singular and 4ti2. Maybe the performance can be increased by use of https://github.com/gap-system/gap-docker-base.

Both are available in `gap-docker`, because `gap-docker` is based on `gap-docker-base`: https://github.com/gap-system/gap-docker/blob/190dc4b8f8074f5d0a2b25088bcc1504746bb70c/Dockerfile#L1

> Same question for CddInterface and NormalizInterface. Maybe those are included in https://github.com/gap-system/gap-docker?

As both are deposited packages, both should be included in `gap-docker`.

**Comment by HereAround** [comment]
I have extended the tests. For some packages the tests complete successfully. For some, I will need to change the installation scripts (e.g. `SpasmInterface).` But I am also at a loss for example for `H0Approximator` and for `TruncationsOfFPGradedModules`. The tests of those are currently executed by the tests. Among others, `TruncationsOfFPGradedModules` raises:

Error, Variable: 'SolveEqualitiesAndInequalitiesOverIntergers' must have an as...

This error indicates, that the gap installation is having trouble accessing the CddInterface.

For H0Approximator, I build two binaries which are placed the the /bin folder of the package. I verified earlier that they are indeed being build. However, for some reason gap cannot seem to find these binaries.

**Comment by HereAround** [comment]
It may not be perfect, but a starting point. I am merging this now in the form discussed last week. (The tests for the H0Approximator do not run yet, but again - a good starting point).

**Pull request merged**
